### ISSUE TITLE
Add external License file in your repo

### ISSUE THREAD

**Issue by SumitCo** [indesignscript/InsertTypographerQuote#2]
Hi
Can you please add an external MIT open source license agreement file or the full agreement file within your script repo .
There are some legal guideline that require this external file. Your support is highly appreciated.

Thanks,
Sumit Garg
Adobe

**Comment by indesignscript** [comment]
Hi Sumit,
I chose the MIT license template from Github. Could you please review. Thanks Stefan

**Comment by SumitCo** [comment]
External license file looks good. Thanks for making this change.
I will create the required pull request to merge this change in Adobe's organization.
